[package]
name = "helix"
version = "0.1.0"
edition = "2021"

[lib]
name = "helix"
crate-type = ["lib", "staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
cpp = [] # defines that the lib will be used from C++
speech = ["dep:tts"]
network = ["dep:tokio"]

[dependencies]
anyhow = "1.0.69"
byteorder = "1.4.3"
cpal = "0.15.0"
imgui = { version = "0.10.0", features = ["docking"] }
imgui-wgpu = "0.22.0"
imgui-winit-support = "0.10.0"
lazy_static = "1.4.0"
libc = "0.2.139"
pollster = "0.3.0"
ringbuf = "0.3.2"
rubato = "0.12.0"
tokio = { version = "1.26.0", features = ["full"], optional = true }
tts = { version = "0.25.0", optional = true }
wgpu = "0.15.1"
