[package]
name = "helix"
version = "0.1.0"
edition = "2021"

[lib]
name = "helix"
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["audio"]
audio = ["dep:byteorder", "dep:cpal", "dep:ringbuf", "dep:rubato"]
speech = ["dep:tts"]
network = ["dep:tokio"]

[dependencies]
byteorder = {version = "1.4.3", optional = true }
cpal = { version = "0.15.0", optional = true }
lazy_static = "1.4.0"
libc = "0.2.139"
ringbuf = { version = "0.3.2", optional = true }
rubato = {version = "0.12.0", optional = true }
tokio = { version = "1.26.0", features = ["full"], optional = true }
tts = { version = "0.25.0", optional = true }
