[package]
name = "helix"
version = "0.1.0"
edition = "2021"

[lib]
name = "helix"
crate-type = ["lib", "staticlib"]

[features]
default = ["f3dex2"]

# Graphics Features
f3dex2 = []
f3dzex2 = ["f3dex2"]

# Additional Features
speech = ["dep:tts"]
network = ["dep:tokio"]

[dependencies]
anyhow = "1.0.70"
arie = "0.1.0"
imgui = { version = "0.10.0", features = ["docking"] }
imgui-wgpu = "0.22.0"
libc = "0.2.139"
pollster = "0.3.0"
sdl2 = { git = "https://github.com/Rust-SDL2/rust-sdl2", revion = "31e830e", features = ["raw-window-handle"] }
tokio = { version = "1.26.0", features = ["full"], optional = true }
tts = { version = "0.25.0", optional = true }
wgpu = "0.15.1"
