[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "linux")'.dependencies]
helix = { path = "../..", features = ["network"] }

[target.'cfg(not(target_os = "linux"))'.dependencies]
helix = { path = "../..", features = ["speech", "network"] }
