name: validate

on: [push, pull_request]

jobs:
  rustfmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run rustfmt
      run: cargo fmt --all -- --check
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update apt
      run: sudo apt update
    - name: Install alsa
      run: |
        sudo apt-get install speech-dispatcher
        sudo apt-get install libasound2-dev
    - name: Build
      run: cargo build --verbose
  macos-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
  windows-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
