name: validate
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rustfmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run cargo fmt
      run: cargo fmt --all -- --check
    - name: Run cargo clippy
      run: cargo fmt --all -- --check
  macos-check:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test --features "speech network"
  ubuntu-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update apt
      run: sudo apt update
    - name: Install alsa
      run: |
        sudo apt-get install libasound2-dev
        sudo apt-get install libspeechd-dev
    - name: Test
      run: cargo test --features "speech network"
  windows-check:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: cargo test --features "speech network"
