name: validate
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rustfmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run cargo fmt
      run: cargo fmt --all -- --check
    - name: Run cargo clippy
      run: cargo fmt --all -- --check
  macos-check:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test (OpenGL)
      run: cargo test --features "speech, network, opengl, f3dex2" --no-default-features
    - name: Test (WGPU)
      run: cargo test --features "speech, network, wgpu, f3dex2" --no-default-features
  ubuntu-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update apt
      run: sudo apt update
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y $(cat .github/workflows/apt-deps.txt)
    - name: Test (OpenGL)
      run: cargo test --features "speech, network, opengl, f3dex2" --no-default-features
    - name: Test (WGPU)
      run: cargo test --features "speech, network, wgpu, f3dex2" --no-default-features
  windows-check:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test (OpenGL)
      run: cargo test --features "speech, network, opengl, f3dex2" --no-default-features
    - name: Test (WGPU)
      run: cargo test --features "speech, network, wgpu, f3dex2" --no-default-features
